/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-communication_simulation
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_COMMUNICATION_SIMULATION_API_H
#define INCLUDED_COMMUNICATION_SIMULATION_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_communication_simulation_EXPORTS
#define COMMUNICATION_SIMULATION_API __GR_ATTR_EXPORT
#else
#define COMMUNICATION_SIMULATION_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_COMMUNICATION_SIMULATION_API_H */
