/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-n3_mac
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_N3_MAC_API_H
#define INCLUDED_N3_MAC_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_n3_mac_EXPORTS
#define N3_MAC_API __GR_ATTR_EXPORT
#else
#define N3_MAC_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_N3_MAC_API_H */
